//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPlayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_BANVEXEKHACHEntities : DbContext
    {
        public QL_BANVEXEKHACHEntities()
            : base("name=QL_BANVEXEKHACHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TAIXE> TAIXEs { get; set; }
        public virtual DbSet<TINHTHANH> TINHTHANHs { get; set; }
        public virtual DbSet<TUYENXE> TUYENXEs { get; set; }
        public virtual DbSet<VEXE> VEXEs { get; set; }
        public virtual DbSet<XE> XEs { get; set; }
    
        [DbFunction("QL_BANVEXEKHACHEntities", "DoanhThuTheoThang")]
        public virtual IQueryable<DoanhThuTheoThang_Result> DoanhThuTheoThang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<DoanhThuTheoThang_Result>("[QL_BANVEXEKHACHEntities].[DoanhThuTheoThang]()");
        }
    }
}
