//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.VEXEs = new HashSet<VEXE>();
        }
    
        public string MANHANVIEN { get; set; }
        public string TENNHANVIEN { get; set; }
        public string SDT { get; set; }
        public string GIOITINH { get; set; }
        public string EMAIL { get; set; }
        public string MATKHAU_NV { get; set; }
        public Nullable<int> NAMSINH { get; set; }
        public string QUYEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEXE> VEXEs { get; set; }
    }
}
