//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUYENXE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUYENXE()
        {
            this.VEXEs = new HashSet<VEXE>();
        }
    
        public string MATUYENXE { get; set; }
        public string TUYEN { get; set; }
        public string MAXE { get; set; }
        public string MATAIXE { get; set; }
        public Nullable<int> SOGHETRONG { get; set; }
        public Nullable<System.TimeSpan> GIOKHOIHANH { get; set; }
        public string DIEMDI { get; set; }
        public string DIEMDEN { get; set; }
    
        public virtual TAIXE TAIXE { get; set; }
        public virtual TINHTHANH TINHTHANH { get; set; }
        public virtual TINHTHANH TINHTHANH1 { get; set; }
        public virtual XE XE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEXE> VEXEs { get; set; }
    }
}
