//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEXE
    {
        public string MAVEXE { get; set; }
        public string MAKHACHHANG { get; set; }
        public string MANHANVIEN { get; set; }
        public string MATUYENXE { get; set; }
        public string TINHTRANG { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
        public Nullable<int> VITRIGHE { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual TUYENXE TUYENXE { get; set; }
    }
}
